const monsters = [
  {
    name: "orange",
    size: "normal",
    level: 0,
    role: "dude",
    source: "book2",
    page: "33",
    notes: "",
    type: "dragon",
    quantity: 0,
  },
  {
    name: "apple",
    size: "large",
    level: 0,
    role: "fighter",
    source: "book1",
    page: "33",
    notes: "",
    type: "humanoid",
    quantity: 0,
  },
  {
    name: "dog",
    size: "large",
    level: 0,
    role: "fighter",
    source: "book1",
    page: "33",
    notes: "",
    type: "humanoid",
    quantity: 0,
  },
  {
    name: "cat",
    size: "large",
    level: 0,
    role: "fighter",
    source: "book1",
    page: "33",
    notes: "",
    type: "humanoid",
    quantity: 0,
  },
  {
    name: "dino",
    size: "large",
    level: 0,
    role: "fighter",
    source: "book1",
    page: "33",
    notes: "",
    type: "humanoid",
    quantity: 0,
  },
  {
    name: "person",
    size: "large",
    level: 0,
    role: "fighter",
    source: "book1",
    page: "33",
    notes: "",
    type: "humanoid",
    quantity: 0,
  },
];

export { monsters };
